### ISSUE TITLE
Issues for files which do not exist

### ISSUE THREAD

**Issue by mrb** [codeclimate/spec#18]
Some static analysis engines emit issues for files which are not a part of the working tree - e.g. some engines will warn you about certain files which don't exist. One way to handle this would be to create a concept of "repo level issues." Another would be to create a way to surface these files in the CC UI and in the CLI. /c @brynary

**Comment by wfleming** [comment]
I feel like this is related enough to the issue @ABaldwinHunter ran into [brakeman](https://github.com/codeclimate/codeclimate-brakeman/pull/4) reporting a missing `protect_from_forgery` (for which there is no line number because it's, you know, missing) that it makes sense to think about the solution to both at once. Basically, there are classes of issues for which a `location` may not reasonably exist, or a file-level `location` (i.e no line number) may exist, but the file itself may not actually exist.

**Comment by mrb** [comment]
@brynary Opinions on how to handle this?

**Comment by fhwang** [comment]
Maybe an optional top-level `scope` key?

````
{
  "type": "issue",
  "scope": "repository"
  ...
}
````

Presumably if you used that then `location` would not be required.
